name: TODO to Issue

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4.11.1
        id: todo
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
